TARGET			?= rootkit_packed

obj-m			+= $(TARGET).o
$(TARGET)-y		+= packer.o

ccflags-y	    += -I$(src)/../header_files
ccflags-y	    += -I$(src)/../../output
ccflags-y		+= $(CFLAGS) -Os -fomit-frame-pointer -fno-stack-protector

KBUILD_CFLAGS	:= $(subst -pg,,$(KBUILD_CFLAGS))
KBUILD_CFLAGS	:= $(subst -mfentry,,$(KBUILD_CFLAGS))
